/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp_9;

import javafx.application.Application;
import javafx.scene.image.Image;
import javafx.stage.Stage;

import java.util.ArrayList;

public class App extends Application{
    private Stage stage;
    private static ArrayList<Profile> profiles = new ArrayList<>();

    public static void addProfile(Profile profile) {
        profiles.add(profile);
    }

    public static ArrayList<Profile> getProfiles() {
        return profiles;
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;

        stage.setTitle("Profile App");

        Image icon = new Image("file:src\\main\\resources\\icon.png");
        stage.getIcons().add(icon);

        HomeScene homeScene = new HomeScene(stage);
        homeScene.show();

        stage.setResizable(false);
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
